### ISSUE TITLE
SNSアイコンが表示されない件について

### ISSUE THREAD

**Issue by hashimotok-mp** [MonsterLifeServer/HomePage#2]
style.scssのℓ82〜ℓ84
```scss
.sns i {
    opacity: 1;
}
```
を
```scss
.sns {
    visibility: visible;
    i {
        opacity: 1;
    }
}
```
にすれば良いはず
